# Robot.
map_frame_id: odom
robot_base_frame_id: base
robot_pose_with_covariance_topic: /pose
robot_pose_cache_size: 50
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /front_camera/depth/color/points
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      type: perfect

track_point_frame_id: base
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 5.0
time_tolerance: 0.001
time_offset_for_point_cloud: 0.0
robot_motion_map_update/covariance_scale: 0.01

# Map.
length_in_x: 5.0
length_in_y: 5.0
position_x: 0.0
position_y: 0.0
resolution: 0.01
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.001
surface_normal_positive_axis: z
fused_map_publishing_rate: 5.
