# Robot.
map_frame_id: odom
robot_base_frame_id: base
robot_pose_with_covariance_topic: /pose
robot_pose_cache_size: 50
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /front_camera/depth/color/points
    queue_size: 1
    publish_on_update: true
    sensor_processor:
      type: structured_light
      cutoff_min_depth: 0.2
      cutoff_max_depth: 3.25
      normal_factor_a: 0.000611
      normal_factor_b: 0.003587
      normal_factor_c: 0.3515
      normal_factor_d: 0
      normal_factor_e: 1
      lateral_factor: 0.01576

track_point_frame_id: base
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
min_update_rate: 3.0
time_tolerance: 1e-3
time_offset_for_point_cloud: 0.0
robot_motion_map_update/covariance_scale: 0.03
scanning_duration: 0.2

# Map.
length_in_x: 5.0
length_in_y: 5.0
position_x: 0.0
position_y: 0.0
resolution: 0.01
min_variance: 0.0001
max_variance: 0.05
mahalanobis_distance_threshold: 2.5
multi_height_noise: 0.001
surface_normal_positive_axis: z
